name: vyana_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.7+1
  flutter_riverpod: ^3.1.0
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  go_router: ^17.0.1
  google_fonts: ^6.3.3
  http: ^1.6.0
  json_annotation: ^4.9.0
  permission_handler: ^12.0.1
  riverpod_annotation: ^4.0.0
  shared_preferences: ^2.5.4
  record: ^5.1.0
  path_provider: ^2.1.1
  http_parser: ^4.0.2
  url_launcher: ^6.3.2
  uuid: ^4.5.2
  supabase_flutter: ^2.12.0
  flutter_local_notifications: ^19.5.0
  audioplayers: ^6.5.1
  timezone: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  riverpod_generator: ^4.0.0+1
  json_serializable: ^6.11.2
  freezed: ^3.2.3
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launch_background"
  ios: true
  image_path: "assets/images/vyana_logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/vyana_logo.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/vyana_logo.png"
    icon_size: 48

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/

dependency_overrides:
  record_linux: ^1.2.1
